- name: installing etcd as a supervised app
  hosts: all

  tasks:
    - name: add etcd user
      user: name=etcd shell=/bin/bash home=/home/etcd

- hosts: all
  remote_user: etcd

  vars:
    supervisor_virtualenv: /home/etcd
    supervisor_home: /home/etcd/supervisor

  roles:
    - role: etcd
      install_dir: /home/etcd

    - role: supervise
      name: etcd
      directory: /home/etcd
      command: /home/etcd/bin/etcd -n {{ ansible_hostname }} -c {{ etcd_client_address }} -s {{ etcd_server_address }} -cl 0.0.0.0 -sl 0.0.0.0
